### PR TITLE
added de/encoding without headers

### PR DESCRIPTION
**Pull request by epsilonhalbe**
Tried to be backwards compatible, but I am not 100% sure.
I coded this quite late at night, so please be thorough when reviewing - I'll clean up if there are any problems, just tell me.

- added .gitignore
- tidied up stack.yaml and moved to lts-8.0
- incremented version number in cabal file 0.8 -> 0.8.1

compiled this successfully with:
- lts-8.0 (ghc-8.0.2)
- lts-7.19 (ghc-8.0.1)
- lts-6.30 (ghc-7.10.3)

### CODE REVIEW

**Comment by alpmestan** [comment]
Your changes introduced some dependency version resolution issues, coud you look into that when you get a chance?

**Comment by phadej** [comment]
It's not this change, it's just `cabal-install` being dummier than needed. Could change to `CABALVER=head`, as it has better solver.

**Comment by alpmestan** [comment]
Oh, sorry then.

**Comment by epsilonhalbe** [comment]
I am getting less familiar with cabal day-by-day as I mostly use `stack` or `nix` though with the latter I am not really familiar, if you want to I can try to change the travis.yaml to work with stack and for GHC head and to use cabal

**Comment by epsilonhalbe** [comment]
ps: I decided to add some convenience aliases - as this is not yet merged

**Comment by epsilonhalbe** [comment]
@alpmestan I did not change anything in the .cabal file except for the version number of servant-cassava, can I somehow give hints to cabal to (manually) help resolving, in order to make the travis build happy?
I can assure you the stack build for ghc 8.0.1, 8.0.2 and 7.10.3 were successful issued no warning.

**Comment by phadej** [comment]
Could you rebase on the current master, I made a few changes to travis.yml.

**Comment by epsilonhalbe** [comment]
thanks for changing the travis - now everything compiled!

**Comment by epsilonhalbe** [comment]
is there anything, still missing/that needs improvements?

**Comment by alpmestan** [comment]
LGTM. @phadej ?

**Comment by phadej** [comment]
Merging, I'll clean up this. @epsilonhalbe how soon do you want a release? (I'm a bit tight on time this week).

**Comment by epsilonhalbe** [comment]
not tight at all - take your time, I just wanted to know if there is still something missing. until the release I put the git repo in my stack yaml and afterwards depend on the release so no problem.

**Pull request merged**
