### PR TITLE
tab separated values

### PR DESCRIPTION
**Pull request by gbaz**
This doesn't add a file, but just does it with typeclasses, as discussed at #10

### CODE REVIEW

**Comment by phadej** [comment]
Looks great. @alpmestan, I think we should have only single class (for both encoding and decoding). I don't really see any benefit in current approach.

And now it get's ugly, as you are forced to define encoding to be able to decode (because of how `Accept` is defined atm).

I can make single-class refactor, if it's ok.

**Comment by alpmestan** [comment]
You mean you want to merge MimeRender and MimeUnrender?!

**Comment by phadej** [comment]
@alpmestan no, merge `EncodeOpts` and `DecodeOpts`. Cassava's, [`DecodeOptions`](http://hackage.haskell.org/package/cassava-0.4.5.1/docs/Data-Csv.html#t:DecodeOptions) can be derived from [`EncodeOptions`](http://hackage.haskell.org/package/cassava-0.4.5.1/docs/Data-Csv.html#t:EncodeOptions).

**Comment by alpmestan** [comment]
Oh, then yes, I agree.

**Comment by phadej** [comment]
I merged this, will refactor into single type-class and cut new major release

**Comment by phadej** [comment]
Released in https://hackage.haskell.org/package/servant-cassava-0.10

**Pull request merged**
